### ISSUE TITLE
`dbt run` failed, unable to create the customers table with jaffle_shop example

### ISSUE THREAD

**Issue by jovezhong** [rockset/dbt-rockset#17]
Greetings,

I am trying the dbt-rockset with dbt 0.21.0 and adapter 0.20.0. Just used the https://github.com/dbt-labs/jaffle_shop example. Nothing changed except the rockset profile. `dbt debug` and `dbt seed` were okay but while running dbt run the customers table failed to be created with the following error message. Please help :pray:

> {"message":"No valid overload found for function / with arguments (string, int)","type":"QueryError","line":null,"column":null,"trace_id":"67a41173-d836-404d-a6c6-870e8da68f83","error_id":"no_valid_overload"}

this seems to be related to the last row of create_table
https://github.com/rockset/dbt-rockset/blob/4d3da2bc17b2bf3c478941ab0c9dd73edec1750b/dbt/adapters/rockset/impl.py#L300

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/5076438/144485365-628c80f1-c129-4a31-b1f2-606ab47b164f.png">

Error log

> 2021-12-02 18:34:47.576113 (Thread-39): Unhandled error while executing model.jaffle_shop.customers
{"message":"No valid overload found for function `/` with arguments (string, int)","type":"QueryError","line":null,"column":null,"trace_id":"67a41173-d836-404d-a6c6-870e8da68f83","error_id":"no_valid_overload"}
2021-12-02 18:34:47.576362 (Thread-39): 
Traceback (most recent call last):
  File "/Users/jove/Dev/dbt-venv/lib/python3.9/site-packages/dbt/task/base.py", line 348, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/Users/jove/Dev/dbt-venv/lib/python3.9/site-packages/dbt/task/base.py", line 291, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/Users/jove/Dev/dbt-venv/lib/python3.9/site-packages/dbt/task/base.py", line 393, in run
    return self.execute(compiled_node, manifest)
  File "/Users/jove/Dev/dbt-venv/lib/python3.9/site-packages/dbt/task/run.py", line 249, in execute
    result = MacroGenerator(materialization_macro, context)()
  File "/Users/jove/Dev/dbt-venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/jove/Dev/dbt-venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/jove/Dev/dbt-venv/lib/python3.9/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/jove/Dev/dbt-venv/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 33, in macro
  File "/Users/jove/Dev/dbt-venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/jove/Dev/dbt-venv/lib/python3.9/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/jove/Dev/dbt-venv/lib/python3.9/site-packages/dbt/adapters/rockset/impl.py", line 300, in create_table
    iis_query_id = self._execute_iis_query_and_wait_for_docs(relation, sql)
  File "/Users/jove/Dev/dbt-venv/lib/python3.9/site-packages/dbt/adapters/rockset/impl.py", line 388, in _execute_iis_query_and_wait_for_docs
    query_id, num_docs_inserted = self._execute_iis_query(relation, sql)
  File "/Users/jove/Dev/dbt-venv/lib/python3.9/site-packages/dbt/adapters/rockset/impl.py", line 404, in _execute_iis_query
    resp = self._send_rs_request('POST', endpoint, body=body)
  File "/Users/jove/Dev/dbt-venv/lib/python3.9/site-packages/dbt/adapters/rockset/impl.py", line 553, in _send_rs_request
    raise Exception(resp.text)
Exception: {"message":"No valid overload found for function `/` with arguments (string, int)","type":"QueryError","line":null,"column":null,"trace_id":"67a41173-d836-404d-a6c6-870e8da68f83","error_id":"no_valid_overload"}
2

**Comment by samecrowder** [comment]
Thanks for the report! I found that it was a simple issue with the data type conversion in our implementation of the `dbt seed` command. I fixed it and pushed a new version of the adapter `0.1.2` which you can download here: https://pypi.org/project/dbt-rockset/0.1.2/

**Comment by samecrowder** [comment]
@jovezhong I ended up finding another issue, so now it's version `0.1.3`

**Comment by jovezhong** [comment]
@samecrowder  Sorry, I didn't get a chance to verify this earlier.

I am not sure whether this adapter now supports dbt v1.0

I had a virtualenv with dbt 0.21.1 and ran with dbt-rockset 0.1.3. Same issue`"error_id":"no_valid_overload`

when I ran `dbt --version` 

`rockset: 0.20.0` is shown, but I ran `pip install --upgrade dbt-rockset` or even `pip uninstall dbt-rockset`

Please advise how to fix it. If the adapter can support dbt v1.0, it'll be even better.
